import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      animation: {
        marquee: "marquee 30s linear infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      colors: {
        "on-primary-fixed": "#0d1c32",
        "surface-tint": "#515f78",
        "on-secondary": "#ffffff",
        primary: "#000000",
        "on-secondary-container": "#785a1a",
        "on-tertiary-fixed": "#1a1c1c",
        "outline-variant": "#c5c6cd",
        "secondary-fixed": "#ffdea5",
        "on-background": "#1a1c1d",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary-fixed": "#261900",
        "tertiary-container": "#1a1c1c",
        tertiary: "#000000",
        "inverse-surface": "#2f3132",
        "on-surface-variant": "#44474d",
        "secondary-container": "#fed488",
        "on-error-container": "#93000a",
        "on-surface": "#1a1c1d",
        secondary: "#775a19",
        "surface-variant": "#e2e2e4",
        background: "#0a1424",
        "inverse-primary": "#b9c7e4",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-low": "#f3f3f5",
        "tertiary-fixed": "#e2e2e2",
        surface: "#12233c",
        "on-primary-fixed-variant": "#39475f",
        "surface-dim": "#d9dadc",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e2e2e4",
        "primary-container": "#0d1c32",
        "on-error": "#ffffff",
        "on-tertiary-container": "#838484",
        "inverse-on-surface": "#f0f0f2",
        "error-container": "#ffdad6",
        "surface-container-high": "#e8e8ea",
        "primary-fixed": "#d6e3ff",
        "on-secondary-fixed-variant": "#5d4201",
        "surface-container": "#eeeef0",
        "surface-bright": "#f9f9fb",
        "primary-fixed-dim": "#b9c7e4",
        outline: "#75777e",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary-container": "#76849f",
        error: "#ba1a1a",
        gold: {
          DEFAULT: "#e9c176",
          hover: "#d1a751",
          dark: "#775a19",
        },
        navy: {
          DEFAULT: "#0a1424",
          surface: "#12233c",
          card: "#101c30",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1200px",
        "margin-desktop": "64px",
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        serif: ["Playfair Display", "Georgia", "serif"],
        display: ["Playfair Display", "Georgia", "serif"],
        heading: ["Playfair Display", "Georgia", "serif"],
        caption: ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
