import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://gnbyrvileybbqfuzgbty.supabase.co';
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'sb_publishable_8p4hyisKhyQaYNJWa6G48Q_DILEiCO7';
const supabase = createClient(supabaseUrl, supabaseKey);

export const dynamic = 'force-dynamic';

function getGenderPrefix(gender?: string | null): string {
  const g = (gender || '').toLowerCase().trim();
  if (g.startsWith('p') || g.startsWith('f') || g.includes('wanita') || g.includes('female')) {
    return 'F-';
  }
  return 'M-';
}

async function withTimeout<T>(promise: PromiseLike<T>, timeoutMs = 4000): Promise<T> {
  return Promise.race([
    promise,
    new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error('DATABASE_TIMEOUT')), timeoutMs)
    ),
  ]);
}

interface ParticipantPayload {
  nama: string;
  email: string;
  no_bib?: string;
  kategori: string;
  jenis_kelamin?: string;
  errors?: string[];
  isValid?: boolean;
  bibAutoGenerated?: boolean;
  [key: string]: any;
}

interface ProcessedParticipant extends ParticipantPayload {
  errors: string[];
}

function extractBibNumber(bib?: string | null): number | null {
  if (!bib) return null;
  const clean = bib.trim();
  const digits = clean.replace(/\D/g, '');
  if (digits) {
    const num = parseInt(digits, 10);
    if (!isNaN(num)) return num;
  }
  return null;
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const participants: ParticipantPayload[] = body.participants || [];
    const forceRegenerateAll = Boolean(body.forceRegenerateAll);

    if (!Array.isArray(participants) || participants.length === 0) {
      return NextResponse.json({ success: true, participants: [] });
    }

    // 1. Fetch all existing BIBs from database
    const queryPromise = supabase
      .from('trailrun_registrations')
      .select('no_bib');

    const { data: dbData } = await withTimeout(queryPromise, 4000).catch(() => ({ data: null }));

    const dbBibSet = new Set<string>();
    let maxDbNumber = 0;

    if (dbData && Array.isArray(dbData)) {
      for (const item of dbData) {
        if (!item.no_bib) continue;
        const clean = item.no_bib.trim().toUpperCase();
        dbBibSet.add(clean);

        const num = extractBibNumber(clean);
        if (num !== null && num > maxDbNumber && num < 100000) {
          maxDbNumber = num;
        }
      }
    }

    // 2. Determine sequence start point
    const batchNums = participants.map((p) => extractBibNumber(p.no_bib));
    const allHaveNums = batchNums.every((n) => n !== null);
    const isConsecutive =
      allHaveNums &&
      batchNums.length > 0 &&
      batchNums.every((n, i) => i === 0 || n === (batchNums[i - 1] as number) + 1);

    let globalSeq = 1;
    if (forceRegenerateAll) {
      if (isConsecutive) {
        // If batch already had clean consecutive numbers, advance to next block
        const highestBatch = Math.max(...(batchNums as number[]));
        const highest = Math.max(maxDbNumber, highestBatch);
        globalSeq = highest >= 99990 ? 1 : highest + 1;
      } else {
        // Was not consecutive (e.g. all 0001 or duplicates) -> start sequentially from lowest available
        globalSeq = maxDbNumber + 1;
      }
    } else {
      globalSeq = maxDbNumber + 1;
    }

    const batchBibSet = new Set<string>();
    const updatedParticipants: ProcessedParticipant[] = participants.map((p) => ({
      ...p,
      errors: [...(p.errors || [])],
      bibAutoGenerated: p.bibAutoGenerated,
    }));

    // 3. First Pass: Validate manual BIBs (if not forced to regenerate)
    if (!forceRegenerateAll) {
      for (let i = 0; i < updatedParticipants.length; i++) {
        const p = updatedParticipants[i];
        let rawBib = (p.no_bib || '').trim().toUpperCase();
        if (/^[FM]\d{5}$/.test(rawBib)) {
          rawBib = `${rawBib[0]}-${rawBib.slice(1)}`;
        }

        if (rawBib) {
          // Enforce exactly 7 characters: F-XXXXX or M-XXXXX
          if (rawBib.length !== 7 || !/^[FM]-\d{5}$/.test(rawBib)) {
            p.errors.push(`Nomor BIB "${rawBib}" harus tepat 7 karakter (format F-XXXXX atau M-XXXXX)`);
            p.isValid = false;
          }
          // Check if already in DB
          else if (dbBibSet.has(rawBib)) {
            p.errors.push(`Nomor BIB "${rawBib}" sudah terdaftar di database oleh peserta lain`);
            p.isValid = false;
          }
          // Check if duplicate within this batch
          else if (batchBibSet.has(rawBib)) {
            p.errors.push(`Nomor BIB "${rawBib}" duplikat dengan baris lain di file Excel`);
            p.isValid = false;
          } else {
            // Valid manual BIB
            batchBibSet.add(rawBib);
            p.no_bib = rawBib;
            p.bibAutoGenerated = false;
          }
        }
      }
    }

    // 4. Second Pass: Assign sequential unique BIB for participants needing one
    for (let i = 0; i < updatedParticipants.length; i++) {
      const p = updatedParticipants[i];
      const hasValidManual =
        !forceRegenerateAll &&
        p.no_bib &&
        batchBibSet.has(p.no_bib.toUpperCase()) &&
        !p.errors.some((e) => e.toLowerCase().includes('bib'));

      if (!hasValidManual) {
        const pref = getGenderPrefix(p.jenis_kelamin);

        // Find next sequential candidate that is neither in DB nor in current batch (F/M + 5 digits, max 6 chars)
        let candidateNum = globalSeq;
        let candidateBib = `${pref}${String(candidateNum).padStart(5, '0')}`;
        let attempts = 0;

        while (
          (dbBibSet.has(candidateBib.toUpperCase()) || batchBibSet.has(candidateBib.toUpperCase())) &&
          attempts < 99999
        ) {
          candidateNum++;
          if (candidateNum > 99999) candidateNum = 1;
          candidateBib = `${pref}${String(candidateNum).padStart(5, '0')}`;
          attempts++;
        }

        globalSeq = candidateNum + 1;
        batchBibSet.add(candidateBib.toUpperCase());

        p.no_bib = candidateBib;
        p.bibAutoGenerated = true;

        // Clear any previous BIB-specific error if now assigned successfully
        p.errors = p.errors.filter((e) => !e.toLowerCase().includes('bib'));
        p.isValid = p.errors.length === 0;
      }
    }

    return NextResponse.json({
      success: true,
      participants: updatedParticipants,
      totalCount: updatedParticipants.length,
    });
  } catch (err: any) {
    console.error('Error in bulk-bib-process route:', err);
    return NextResponse.json(
      { success: false, error: err.message || 'Gagal memproses validasi BIB kolektif' },
      { status: 500 }
    );
  }
}
